"use strict";
const usersSchema = `
    id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    deactivated TEXT,
    about TEXT,
    activities TEXT,
    bdate TEXT,
    books TEXT,
    career_group_id TEXT,
    career_company TEXT,
    career_country_id TEXT,
    career_city_id TEXT,
    career_city_name TEXT,
    career_from TEXT,
    career_until TEXT,
    career_position TEXT,
    city_id INTEGER,
    city_title TEXT,
    communities TEXT,
    country_id INTEGER,
    country_title TEXT,
    domain TEXT,
    education_form TEXT,
    education_status TEXT,
    facebook INTEGER,
    facebook_name TEXT,
    faculty INTEGER,
    faculty_name TEXT,
    followers_count INTEGER,
    friends TEXT,
    games TEXT,
    graduation INTEGER,
    has_mobile INTEGER,
    has_photo INTEGER,
    home_phone TEXT,    
    home_town TEXT,
    instagram TEXT,
    interests TEXT,
    last_seen_time INTEGER,
    last_seen_platform INTEGER,
    livejournal TEXT,
    maiden_name TEXT,
    military_unit TEXT,
    military_unit_id TEXT,
    military_country_id TEXT,
    military_from TEXT,
    military_until TEXT,
    mobile_phone TEXT,    
    movies TEXT,
    music TEXT,
    nickname TEXT,
    occupation_type TEXT,
    occupation_id INTEGER,
    occupation_name TEXT,
    online INTEGER,
    online_mobile INTEGER,
    online_app INTEGER,
    personal_political INTEGER,
    personal_langs TEXT,
    personal_religion TEXT,
    personal_inspired_by TEXT,
    personal_people_main INTEGER,
    personal_life_main INTEGER,
    personal_smoking INTEGER,
    personal_alcohol INTEGER,
    quotes TEXT,
    relatives_id TEXT,
    relatives_name TEXT,
    relatives_type TEXT,
    relation INTEGER,
    relation_partner_id INTEGER,
    relation_partner_first_name TEXT,
    relation_partner_last_name TEXT,
    schools_id TEXT,
    schools_country TEXT,
    schools_city TEXT,
    schools_name TEXT,
    schools_year_from TEXT,
    schools_year_to TEXT,
    schools_year_graduated TEXT,
    schools_class TEXT,
    schools_speciality TEXT,
    schools_type TEXT,
    schools_type_str TEXT,
    screen_name TEXT,
    sex INTEGER,
    site TEXT,
    skype TEXT,
    status TEXT,
    status_audio_album_id INTEGER,
    status_audio_artist TEXT,
    status_audio_date INTEGER,
    status_audio_duration INTEGER,
    status_audio_genre_id INTEGER,
    status_audio_id INTEGER,
    status_audio_is_hq TEXT,
    status_audio_lyrics_id INTEGER,
    status_audio_owner_id INTEGER,
    status_audio_title TEXT,
    status_audio_url TEXT,
    trending INTEGER,
    tv TEXT,
    twitter TEXT,
    universities_id TEXT,
    universities_country TEXT,
    universities_city TEXT,
    universities_name TEXT,
    universities_faculty TEXT,
    universities_faculty_name TEXT,
    universities_chair TEXT,
    universities_chair_name TEXT,
    universities_graduation TEXT,
    universities_education_form TEXT,
    universities_education_status TEXT,
    university INTEGER,
    university_name TEXT,
    verified INTEGER
`;

const communitiesSchema = `
    id INTEGER PRIMARY KEY,
    name TEXT,
    screen_name TEXT,
    is_closed INTEGER,
    type TEXT,
    members_count INTEGER,
    verified INTEGER,
    activity TEXT,
    age_limits INTEGER,
    description TEXT,
    status TEXT,
    trending INTEGER
`;
// age_limits: 1 - none, 2 - 16+, 3 - 18+

module.exports = {
    usersSchema,
    communitiesSchema
};
